/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.yourcompany.yourproject;

public class Usuario {
    
    public static void main(String[] args) {
        
        SmartTv smarTv = new SmartTv();

        System.out.println("A TV está ligada? " + smarTv.ligada);
        System.out.println("Nº de canal: " + smarTv.canal);
        System.out.println("Nível de volume: " + smarTv.volume);

        System.out.println("____________________________________________________");
        smarTv.ligar();
        System.out.println("Novo status -> A TV está ligada? " + smarTv.ligada);

        smarTv.desligar();
        System.out.println("Novo status -> A TV está ligada? " + smarTv.ligada);

        smarTv.aumentarVolume();
        System.out.println("Volume aumentado para: " + smarTv.volume);

        smarTv.diminuirVolume();
        System.out.println("Volume diminuido para: " + smarTv.volume);

        smarTv.mudarCanal();
        System.out.println("Novo canal: " + smarTv.canal);

    }
}
